stages:
  train:
    cmd: python src/main.py
    deps:
      - data/
      - src/main.py
      - src/utils.py
      - params.yaml
    outs:
      - models/model.pt
      - reports/train_params.yaml:
          cache: false
    metrics:
      - reports/train_metrics.csv:
          cache: false